### ISSUE TITLE
Spam en la Consola por BungeeCord

### ISSUE THREAD

**Issue by CroaBeast** [KarmaConfigs/page#10]
Hi, esto me ha estado saliendo estos dos últimos días en la consola del lobby, ¿sabe que es? 
La versión del plugin es 3.3.2
```
[Fri, 26. Jun 2020 00:03:42 EDT INFO] EliasCrack[/] logged in with entity id 59 at ([lobby]-10.5, 18.0, 0.5)
[Fri, 26. Jun 2020 00:03:43 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:43 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:43 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:43 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:43 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:43 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:44 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:44 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:45 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:45 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:46 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:46 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:47 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:47 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:48 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:48 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:49 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:49 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:50 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:50 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:51 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:51 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:52 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:52 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:53 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:53 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:54 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:54 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:55 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:55 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:56 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:56 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:57 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:57 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:58 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:58 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:03:59 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:03:59 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:00 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:00 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:01 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:01 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:02 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:02 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:03 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:03 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:04 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:04 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:05 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:05 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:06 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:06 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:07 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:07 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:08 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:08 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:09 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:09 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:10 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:10 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:11 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:11 EDT INFO] java.lang.NullPointerException
[Fri, 26. Jun 2020 00:04:12 EDT INFO] [ LockLogin ] ( ERROR ) Error while reading a plugin message from BungeeCord
[Fri, 26. Jun 2020 00:04:12 EDT INFO] java.lang.NullPointerException
```

**Comment by KarmaConfigs** [comment]
Mira en la consola de bungeecord, y dime si sale algún error, también me gustaría saber la versión del servidor

**Comment by CroaBeast** [comment]
Por Bungeecord no sale nada, ya sea por cambiar de servers o por logearse, en el lobby y survival aparece ese error. El Lobby y Survival están en la 1.15.2 PaperMC

**Comment by KarmaConfigs** [comment]
> Por Bungeecord no sale nada, ya sea por cambiar de servers o por logearse, en el lobby y survival aparece ese error. El Lobby y Survival están en la 1.15.2 PaperMC

En ese caso, miraré a ver que puede estar pasando, por lo que sé, no hay ninguna razón por la que esto te esté pasando, por tanto, me llevará un tiempo, mientras tanto, prueba a cambiar la configuración de LockLogin en bungeecord

**Comment by CroaBeast** [comment]
Ahora me sale esto en la consola del bungeecord, espero que pueda ayudarlo con lo del bug:
```
[11:13:11] [Netty Worker IO Thread #1/INFO]: [ LockLogin ] ( ERROR ) An error occurred while retrieving IPs data from LockLogin IP database
[11:13:11] [Netty Worker IO Thread #1/INFO]: java.lang.ArrayIndexOutOfBoundsException: 1
[11:13:11] [Netty Worker IO Thread #1/ERROR]: java.lang.ArrayIndexOutOfBoundsException: 1
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at ml.karmaconfigs.LockLogin.IPStorage.IPStorager.getStorage(IPStorager.java:388)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at ml.karmaconfigs.LockLogin.BungeeCord.Events.JoinRelated.onJoin(JoinRelated.java:95)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:389)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.UserConnection.connect(UserConnection.java:285)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.UserConnection.connect(UserConnection.java:276)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.UserConnection.connect(UserConnection.java:251)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.UserConnection.connect(UserConnection.java:204)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:344)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:122)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:93)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:303)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:417)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:13:11] [Netty Worker IO Thread #1/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KarmaConfigs** [comment]
Ya estoy trabajando en ese error, no se donde ni porqué ahora, pero estoy haciendo todo lo posible

**Comment by KarmaConfigs** [comment]
Una cosa, podrías mandarme en un .zip, todos los logs de LockLogin que tengas (Spigot y BungeeCord), los logs se crean en:

LockLogin/logs

**Comment by CroaBeast** [comment]
Aquí les dejo todos los que hay
[login logs.zip](https://github.com/KarmaConfigs/page/files/4842823/login.logs.zip)

**Comment by KarmaConfigs** [comment]
Que versión de Java utilizas?

**Comment by CroaBeast** [comment]
1.15 en el lobby y 1.15.2 en Survival. Y la última versión de BungeeCord

**Comment by KarmaConfigs** [comment]
Nono, la versión de Java, no de spigot ni del plugin

**Comment by CroaBeast** [comment]
Como que versión de Java? La versión del cliente que yo uso para entrar al servidor?
Si es así, uso Optifine 1.15.2 sus pre releases, y la versión normal 1.15.2 y 1.16.1

**Comment by KarmaConfigs** [comment]
No, la versión de Java que usa tu ordenador/VPS

**Comment by CroaBeast** [comment]
Oh... Dice Versión 8 actualización 251

**Comment by KarmaConfigs** [comment]
https://www.java.com/es/download/help/version_manual.xml#:~:text=Versi%C3%B3n%20de%20Java%20en%20el%20panel%20de%20control%20de%20Java,panel%20de%20control%20de%20Java.&text=En%20la%20pesta%C3%B1a%20General%20en,con%20la%20versi%C3%B3n%20de%20Java.

**Comment by CroaBeast** [comment]
El Host lo compré en TheMinecraftHosting, como hago para saber que versión de java usa el host?

**Comment by KarmaConfigs** [comment]
Pregunta en el soporte de tu host

**Comment by CroaBeast** [comment]
Ya creé un ticket, ahora estoy esperando su respuesta

**Comment by CroaBeast** [comment]
Ahora tengo este problema en el BungeeCord:
```
30.06 20:48:16 [Server] INFO [ LockLogin ] ( ERROR ) An error occurred while retrieving IPs data from LockLogin IP database
30.06 20:48:16 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 1
30.06 20:48:16 [Server] INFO [leeicker13] -> UpstreamBridge has disconnected
```

**Comment by KarmaConfigs** [comment]
Vale, tienes discord?, es que necesito un archivo que contiene información difrazada, pero como todo, se puede descifrar, y compartir ese archivo por aquí sería muy peligroso (necesito dicho archivo para verificar si está corrompido o no)

**Comment by CroaBeast** [comment]
Claro, mi discord es CroaBeast#6144

**Comment by KarmaConfigs** [comment]
> Claro, mi discord es CroaBeast#6144

Ya te he enviado la solicitud, soy "The purple man"

**Comment by CroaBeast** [comment]
Ya fue arreglado, gracias nwn
