### ISSUE TITLE
ERROR LockLogin velocity-1.1.5 

### ISSUE THREAD

**Issue by wangwang-code** [KarmaConfigs/page#19]
LockLogin-1.1.0.9 + velocity-1.1.5 +java8
![1](https://user-images.githubusercontent.com/64469117/119259505-35e32580-bc01-11eb-9b9d-f9704a8aa5fd.png)
```
[19:55:47 ERROR]: Can't create plugin locklogin
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.nio.file.Path was bound.
  Did you mean?
    java.nio.file.Path annotated with interface com.velocitypowered.api.plugin.annotation.DataDirectory bound  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:51)

  while locating java.nio.file.Path
    for the 3rd parameter of ml.karmaconfigs.lockloginsystem.velocity.Main.<init>(Main.java:32)
  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:48)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554) ~[velocity-1.1.5.jar:1.1.5]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161) ~[velocity-1.1.5.jar:1.1.5]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108) ~[velocity-1.1.5.jar:1.1.5]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[velocity-1.1.5.jar:1.1.5]
        at com.google.inject.Guice.createInjector(Guice.java:69) ~[velocity-1.1.5.jar:1.1.5]
        at com.google.inject.Guice.createInjector(Guice.java:59) ~[velocity-1.1.5.jar:1.1.5]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119) ~[velocity-1.1.5.jar:1.1.5]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152) ~[velocity-1.1.5.jar:1.1.5]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:283) ~[velocity-1.1.5.jar:1.1.5]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:225) ~[velocity-1.1.5.jar:1.1.5]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:75) ~[velocity-1.1.5.jar:1.1.5]
```

Normal in [snap](https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608), except (Google Translate)
```
[Snap]: Event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=null, connection=de.themoep.snap.forwarding.SnapPlayer$1@770e622) took 4,528ms to process!
```
Waiting for the joining world for a long time (Google Translate)

**Comment by KarmaConfigs** [comment]
> LockLogin-1.1.0.9 + velocity-1.1.5 +java8
> ![1](https://user-images.githubusercontent.com/64469117/119259505-35e32580-bc01-11eb-9b9d-f9704a8aa5fd.png)
> 
> ```
> [19:55:47 ERROR]: Can't create plugin locklogin
> com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) No implementation for java.nio.file.Path was bound.
>   Did you mean?
>     java.nio.file.Path annotated with interface com.velocitypowered.api.plugin.annotation.DataDirectory bound  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:51)
> 
>   while locating java.nio.file.Path
>     for the 3rd parameter of ml.karmaconfigs.lockloginsystem.velocity.Main.<init>(Main.java:32)
>   at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:48)
> 
> 1 error
>         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554) ~[velocity-1.1.5.jar:1.1.5]
>         at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161) ~[velocity-1.1.5.jar:1.1.5]
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108) ~[velocity-1.1.5.jar:1.1.5]
>         at com.google.inject.Guice.createInjector(Guice.java:87) ~[velocity-1.1.5.jar:1.1.5]
>         at com.google.inject.Guice.createInjector(Guice.java:69) ~[velocity-1.1.5.jar:1.1.5]
>         at com.google.inject.Guice.createInjector(Guice.java:59) ~[velocity-1.1.5.jar:1.1.5]
>         at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119) ~[velocity-1.1.5.jar:1.1.5]
>         at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152) ~[velocity-1.1.5.jar:1.1.5]
>         at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:283) ~[velocity-1.1.5.jar:1.1.5]
>         at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:225) ~[velocity-1.1.5.jar:1.1.5]
>         at com.velocitypowered.proxy.Velocity.main(Velocity.java:75) ~[velocity-1.1.5.jar:1.1.5]
> ```
> 
> Normal in [snap](https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608), except (Google Translate)
> 
> ```
> [Snap]: Event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=null, connection=de.themoep.snap.forwarding.SnapPlayer$1@770e622) took 4,528ms to process!
> ```
> 
> Waiting for the joining world for a long time (Google Translate)

Please use release candidate version, which has support with velocity ( LockLogin 1.1.0.9 doesn't )

Download release candidate version from: https://github.com/KarmaConfigs/updates/raw/master/LockLogin/rc/LockLogin.jar
